# Notice: This template has only been tested 
# under Python27 + GAE standard environment
application: aerial-chimera-211120
version: 2
runtime: python27
# threadsafe is required but can be either true or 
# false. For some package, it should be true e.g. Flask
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: helloworld.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest 
- name: ssl
  version: latest
- name: MySQLdb
  version: latest

beta_settings:
    cloud_sql_instances: aerial-chimera-211120:europe-west2:sporteventdb